"""
    Battery Data API

    A standard API for accessing battery experiment datasets and metadata  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: martin.robinson@cs.ox.ac.uk
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.column import Column


class TestColumn(unittest.TestCase):
    """Column unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumn(self):
        """Test Column"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Column()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
