# coding: utf-8

"""
    Battery Data API

    A standard API for accessing battery experiment datasets and metadata  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: martin.robinson@cs.ox.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.column import Column  # noqa: E501
from swagger_client.rest import ApiException


class TestColumn(unittest.TestCase):
    """Column unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumn(self):
        """Test Column"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.column.Column()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
