# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Column(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, unit: str=None):  # noqa: E501
        """Column - a model defined in Swagger

        :param id: The id of this Column.  # noqa: E501
        :type id: int
        :param name: The name of this Column.  # noqa: E501
        :type name: str
        :param unit: The unit of this Column.  # noqa: E501
        :type unit: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'unit': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'unit': 'unit'
        }
        self._id = id
        self._name = name
        self._unit = unit

    @classmethod
    def from_dict(cls, dikt) -> 'Column':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Column of this Column.  # noqa: E501
        :rtype: Column
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Column.


        :return: The id of this Column.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Column.


        :param id: The id of this Column.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Column.


        :return: The name of this Column.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Column.


        :param name: The name of this Column.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def unit(self) -> str:
        """Gets the unit of this Column.


        :return: The unit of this Column.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this Column.


        :param unit: The unit of this Column.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit
